
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anupama Dikkumbura
 */
public class Orders extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Object[][] data = null;
    String [] columNames = new String[4];
    int totalPrice = 0;
    
    /**
     * Creates new form Home
     */
    public Orders() {
        initComponents();
        con=DBconnect.getconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        billOrder = new javax.swing.JButton();
        printBill = new javax.swing.JButton();
        newOrder = new javax.swing.JButton();
        addMore = new javax.swing.JButton();
        totalP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 650, 320));

        billOrder.setBackground(new java.awt.Color(0, 0, 0));
        billOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        billOrder.setForeground(new java.awt.Color(255, 255, 255));
        billOrder.setText("Bill Order");
        billOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billOrderActionPerformed(evt);
            }
        });
        getContentPane().add(billOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 130, 40));

        printBill.setBackground(new java.awt.Color(0, 0, 0));
        printBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printBill.setForeground(new java.awt.Color(255, 255, 255));
        printBill.setText("Print Bill");
        printBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillActionPerformed(evt);
            }
        });
        getContentPane().add(printBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 110, 40));

        newOrder.setBackground(new java.awt.Color(0, 0, 0));
        newOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newOrder.setForeground(new java.awt.Color(255, 255, 255));
        newOrder.setText("New order");
        newOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderActionPerformed(evt);
            }
        });
        getContentPane().add(newOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 150, 60));

        addMore.setBackground(new java.awt.Color(0, 0, 0));
        addMore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addMore.setForeground(new java.awt.Color(255, 255, 255));
        addMore.setText("Add More");
        addMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoreActionPerformed(evt);
            }
        });
        getContentPane().add(addMore, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 150, 60));

        totalP.setBackground(new java.awt.Color(0, 0, 0));
        totalP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(totalP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 189, 63));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TOTAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 121, 44));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 573, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 16, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel5.setText("jLabel1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderActionPerformed
        // TODO add your handling code here:
        columNames = new String[] {"Product Id","Product Name","Quantity","Price"};
        data = new Object[1][4];
        String id = JOptionPane.showInputDialog("Enter Product Id");
        String quantity = JOptionPane.showInputDialog("Enter Quantity");
        try{
            String sql = "Select * from products where pid=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id.toString());
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                data[0][0] = id;
                data [0][2] = quantity;
                data [0][1] = rs.getString("name");
                String a = data[0][2].toString();
                int b = Integer.parseInt(a);
                data [0][3] = rs.getInt("price")*b;
                String priceS = data[0][3].toString();
                totalP.setText(priceS);
                totalPrice =Integer.parseInt(priceS);
            }else{
                JOptionPane.showMessageDialog(null,"No Product found!");
            }
       
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        //data [0][2] = JOptionPane.showInputDialog("Enter price");
        //data [0][3] = JOptionPane.showInputDialog("Enter price");
        
        orderTable.setModel(new DefaultTableModel(data,columNames));
    }//GEN-LAST:event_newOrderActionPerformed

    private void addMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoreActionPerformed
        // TODO add your handling code here:
        Object[][] temp = new Object[data.length+1][4];
        for(int i=0;i<data.length;i++){
            for(int j=0;j<4;j++){
                temp[i][j] = data[i][j];
            }
        }
        String id = JOptionPane.showInputDialog("Enter Product Id");
        String quantity = JOptionPane.showInputDialog("Enter Quantity");
        try{
            String sql = "Select * from products where pid=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id.toString());
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                temp[data.length][0] = id;
                temp [data.length][2] = quantity;
                temp [data.length][1] = rs.getString("name");
                String a = temp[data.length][2].toString();
                int b = Integer.parseInt(a);
                temp [data.length][3] = rs.getInt("price")*b;
                String priceS = temp[data.length][3].toString();
                totalPrice =totalPrice + Integer.parseInt(priceS);
                int abc = totalPrice;
                priceS = String.valueOf(abc);
                totalP.setText(priceS);
                data = temp;
                orderTable.setModel(new DefaultTableModel(data,columNames));
            }else{
                JOptionPane.showMessageDialog(null,"No Product found!");
            }
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
        
    }//GEN-LAST:event_addMoreActionPerformed

    private void billOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billOrderActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/rad","root","");
            int rows = orderTable.getRowCount();
            String orderNames = "";
            for(int i= 0; i<rows;i++){
                orderNames = orderNames + "," + orderTable.getValueAt(i, 1).toString();
            }
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            String date = dtf.format(now);
            Statement pst = con.createStatement();
            pst.executeUpdate("insert into orders(id,date,products,total) Values (null, '"+date+"', '"+orderNames+"', '"+totalPrice+"')");
            
        }catch(Exception e){
            System.out.println("Error");
        }
    }//GEN-LAST:event_billOrderActionPerformed

    private void printBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillActionPerformed
        MessageFormat header = new MessageFormat("Bill");
        String total = "Total = " + String.valueOf(totalPrice);
        MessageFormat footer = new MessageFormat(total);
        
        try{
            orderTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannto print %s%N", e.getMessage());
        }
    }//GEN-LAST:event_printBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMore;
    private javax.swing.JButton billOrder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newOrder;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton printBill;
    private javax.swing.JLabel totalP;
    // End of variables declaration//GEN-END:variables
}
