/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sachini Nayanathara
 */
public class supplier extends javax.swing.JFrame {

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSupplier = new javax.swing.JButton();
        viewSupplier = new javax.swing.JButton();
        updateSupplier = new javax.swing.JButton();
        deleteSupplier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSupplier.setBackground(new java.awt.Color(0, 0, 0));
        addSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addSupplier.setForeground(new java.awt.Color(255, 255, 255));
        addSupplier.setText("Add Supplier");
        addSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(addSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 210, 50));

        viewSupplier.setBackground(new java.awt.Color(0, 0, 0));
        viewSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewSupplier.setForeground(new java.awt.Color(255, 255, 255));
        viewSupplier.setText("View Supplier");
        viewSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(viewSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 210, 50));

        updateSupplier.setBackground(new java.awt.Color(0, 0, 0));
        updateSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateSupplier.setForeground(new java.awt.Color(255, 255, 255));
        updateSupplier.setText("Update Supplier");
        updateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(updateSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 210, 50));

        deleteSupplier.setBackground(new java.awt.Color(0, 0, 0));
        deleteSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteSupplier.setForeground(new java.awt.Color(255, 255, 255));
        deleteSupplier.setText("Delete Supplier");
        deleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(deleteSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierActionPerformed
        // TODO add your handling code here:
        AddSupplier addsupplier = new AddSupplier();
        addsupplier.setVisible(true);
    }//GEN-LAST:event_addSupplierActionPerformed

    private void viewSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierActionPerformed
        // TODO add your handling code here:
        ViewSupplier viewsupplier = new ViewSupplier();
        viewsupplier.setVisible(true);
    }//GEN-LAST:event_viewSupplierActionPerformed

    private void updateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplierActionPerformed
        // TODO add your handling code here:
        UpdateSupplier updatesupplier = new UpdateSupplier();
        updatesupplier.setVisible(true);
    }//GEN-LAST:event_updateSupplierActionPerformed

    private void deleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSupplierActionPerformed
        // TODO add your handling code here:
        DeleteSupplier deletesupplier = new DeleteSupplier();
        deletesupplier.setVisible(true);
    }//GEN-LAST:event_deleteSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupplier;
    private javax.swing.JButton deleteSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateSupplier;
    private javax.swing.JButton viewSupplier;
    // End of variables declaration//GEN-END:variables
}
