
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sachini Nayanathara
 */
public class UpdateSupplier extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form UpdateSupplier
     */
    public UpdateSupplier() {
        initComponents();
        con=DBconnect.getconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sidLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        ClearBtn = new javax.swing.JButton();
        updateSupplier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tpTxt = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        sidTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Update Supplier");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 217, 42));

        sidLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sidLabel.setText("S.ID");
        getContentPane().add(sidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 150, 31));

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 191, 300, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 210, 32));

        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        getContentPane().add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 262, 300, 40));

        ClearBtn.setBackground(new java.awt.Color(0, 0, 0));
        ClearBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 120, 50));

        updateSupplier.setBackground(new java.awt.Color(0, 0, 0));
        updateSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateSupplier.setForeground(new java.awt.Color(255, 255, 255));
        updateSupplier.setText("Update");
        updateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(updateSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 130, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 160, 28));
        getContentPane().add(tpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 343, 300, 40));

        Name1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name1.setText("Name");
        getContentPane().add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -90, 210, 640));

        sidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidTxtActionPerformed(evt);
            }
        });
        getContentPane().add(sidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 121, 300, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel5.setText("jLabel1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        sidTxt.setText("");
        nameTxt.setText("");
        addressTxt.setText("");
        tpTxt.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void updateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSupplierActionPerformed
        // TODO add your handling code here:
        try{
            String sid = sidTxt.getText();
            String sname = nameTxt.getText();
            String address = addressTxt.getText();
            String a = tpTxt.getText();
            int tp = Integer.parseInt(a);
            Statement pst = con.createStatement();
            pst.executeUpdate("update suppliers set name='"+sname+"', address='"+address+"', tp='"+tp+"' where sid='"+sid+"'");
            JOptionPane.showMessageDialog(null, "Supplier Updated");
            nameTxt.setText("");
            addressTxt.setText("");
            tpTxt.setText("");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateSupplierActionPerformed

    private void sidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel Name1;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel sidLabel;
    private javax.swing.JTextField sidTxt;
    private javax.swing.JTextField tpTxt;
    private javax.swing.JButton updateSupplier;
    // End of variables declaration//GEN-END:variables
}
